import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    ELEVEN_LABS_API_KEY = os.getenv("ELEVEN_LABS_API_KEY")
    SYNCLABS_API_KEY = os.getenv("SYNCLABS_API_KEY")
    MONGO_DB_URL = os.getenv("MONGO_DB_URL")
    MONGO_DB_NAME = os.getenv("MONGO_DB_NAME")
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_S3_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME")
    CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
    CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
    CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    SECRET_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
    ALGORITHM = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES = 1440
    SMTP_SERVER=os.getenv("SMTP_SERVER")
    SMTP_PORT=os.getenv("SMTP_PORT")
    SMTP_USERNAME=os.getenv("SMTP_USERNAME")
    # SMTP_PASSWORD="LugaAI123?!#"
    # SMTP_PASSWORD="LugaAI2024"
    SMTP_PASSWORD=os.getenv("SMTP_PASSWORD")
    STRIPE_API_KEY=os.getenv("STRIPE_API_KEY")
    FRONTEND_URL=os.getenv("FRONTEND_URL")
    STRIPE_PUBLIC_KEY=os.getenv("STRIPE_PUBLIC_KEY")
    STRIPE_WEBHOOK=os.getenv("STRIPE_WEBHOOK")
    STRIPE_WEBHOOK_SECRET=os.getenv("STRIPE_WEBHOOK_SECRET")
    S3_PROVIDER = os.getenv("S3_PROVIDER", "CLOUDINARY")
    # BAIDU
    BAIDU_BOS_ENDPOINT = os.getenv("BAIDU_BOS_ENDPOINT")
    BAIDU_BOS_ACCESS_KEY_ID = os.getenv("BAIDU_BOS_ACCESS_KEY_ID")
    BAIDU_BOS_SECRET_ACCESS_KEY = os.getenv("BAIDU_BOS_SECRET_ACCESS_KEY")
    BAIDU_BOS_BUCKET_NAME = os.getenv("BAIDU_BOS_BUCKET_NAME", "luga-ai-bucket")
    GROK_API_KEY = os.getenv("GROK_API_KEY")
    DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
